apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-pdbz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbsa-tenant/rhtap-demo-app/hacbs-test-project-pdbz@sha256:abdb3d2c373e7ceb6082f91165c2da950d1ed7a800d6fa884c4066b3e5b268d1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
