apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-pdbz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-pdbz
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-pdbz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-pdbz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-pdbz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-fbsa-tenant/rhtap-demo-app/hacbs-test-project-pdbz@sha256:abdb3d2c373e7ceb6082f91165c2da950d1ed7a800d6fa884c4066b3e5b268d1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
